# Generated by Django 4.1 on 2022-09-15 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming_app.category'),
        ),
    ]
